# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: FEniCS'24 Conference
    url: workshops/2024
    weight: 10
  - name: Download
    url: download
    weight: 20
  - name: Docs
    url: docs
    weight: 30
  - name: Community
    url: community
    weight: 40
  - name: Community
    url: community
    weight: 50
  - name: Citing
    url: cite
    weight: 60
